### ISSUE TITLE
How to start a desktop? [Fedora/VirtualBox]

### ISSUE THREAD

**Issue by liloman** [wholebits/baseboxes#1]
Hi, 

I've just tried your fedora images but I can't start the desktop in VirtualBox. 
I've tried with:

```bash
dnf group install lxde-desktop
systemct set-default graphical.target
```
But no luck. :(

It's really a shame that there isn't Fedora desktop boxes anymore.

**Comment by wmoldwin** [comment]
Because the base box is built as a server installation, the installed VirtualBox Guest Additions don't contain the graphic desktop components so there's no vboxvideo graphics driver present in the image. Also, the LXDE Desktop group doesn't actually install the base X Windows components so you have to do that yourself.

You'll need to install all of the desktop packages and some development tools and then reinstall VirtualBox Guest Additions to get the graphical components. You'll also need to make sure your kernel is up-to-date first as the `kernel` and `kernel-devel` packages need to be the same version as the currently running kernel for the guest additions to build.

```
# dnf -y upgrade
# reboot
[...]
# dnf -y group install base-x lxde-desktop
# dnf -y install gcc kernel-devel
# curl -O http://download.virtualbox.org/virtualbox/5.1.12/VBoxGuestAdditions_5.1.12.iso
# mount -r VBoxGuestAdditions_5.1.12.iso /mnt
# /mnt/VBoxLinuxAdditions.run
# systemctl set-default graphical.target
# reboot
```

**Comment by liloman** [comment]
Thank you very much. :)

I will try it when I can.

Nice answer, it worthes a gist. ;)
